repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.26
    hooks:
      - id: uv-lock